name: WolvSK
main: fr.nashoba24.wolvsk.WolvSK
author: Nashoba24
version: 1.6.2
depends: [Skript]
softdepend: [ASkyBlock, EssentialsX, GuardianBeamAPI, PlayerPoints, ProtocolLib, SuperTrails]
commands:
  minigames:
    description: Minigames command