command /test:
	trigger:
		open an anvil gui named "Test" to player with default text "Write what you want!"
		
on close anvil gui named "Test":
	broadcast "%player% wrote %event-text%!"

command /testgui:
	trigger:
		open anvil gui named "Hey" to player with default text "&4How are you %player%?" and item golden sword with lore "Type what you want||in the text input :p||(but don't swear please)"

on close anvil gui named "Hey":
	broadcast "%player% answer: %event-text%"
