command /test:
	trigger:
		open an anvil gui named "Test" to player with default text "Write what you want!"
		
on close anvil gui named "Test":
	broadcast "%player% wrote %event-text%!"

command /testgui:
	trigger:
		open anvil gui named "Hey" to player with default text "&4How are you %player%?" and item golden sword

on close anvil gui named "Hey":
	broadcast "%player% answer: %event-text%"

on close anvil gui:
	broadcast "%name of anvil gui% | %input text of anvil gui%"
